### PR TITLE
DRIVERS-2726: Use Ubuntu 22.04

### PR DESCRIPTION
**Pull request by alcaeus**
DRIVERS-2726

I skipped node 16 as well as the .NET driver as that had issues in my testing and should be updated separately. I ran a patch with a single Atlas and a single Kind task, which all passed successfully: https://spruce.mongodb.com/version/6530f40e9ccd4e89b0cdcf5c

### CODE REVIEW

**Comment by alcaeus** [comment]
Note: test failures are unrelated and appear in unmodified patch builds as well.

@jyemin @JamesKovacs @comandeo can you investigate your drivers to see what's happening there?

**Comment by blink1073** [comment]
This has become more urgent: 

https://spruce.mongodb.com/task/drivers_atlas_testing_tests_c__driver~c_master_platform~ubuntu_18.04_runtime~c_clang_validate_workload_executor_patch_57c3b15682dd2c42d8c79338c1f0c13ddf4dac5e_65c19c46562343a4b1321bc8_24_02_06_02_41_11/logs?execution=0

```
[2024/02/05 20:44:11.006] linux-ubuntu-18.04-x86_64
[2024/02/05 20:44:11.007] http://downloads.10gen.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1804-7.2.0.tgz
[2024/02/05 20:44:16.083] curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by Jibola** [comment]
For this newest push are the failures still unrelated?

**Comment by alcaeus** [comment]
.NET, Java, and Ruby are "expected" failing due to some incompatibility with Ubuntu 22.04. We can exclude those from the initial pull request and create downstream tickets for the teams to get the issue sorted. Node was a setup failure, and I've restarted the build as it was previously passing. We'll see where this goes.

**Comment by Jibola** [comment]
> .NET, Java, and Ruby are "expected" failing due to some incompatibility with Ubuntu 22.04. We can exclude those from the initial pull request and create downstream tickets for the teams to get the issue sorted. Node was a setup failure, and I've restarted the build as it was previously passing. We'll see where this goes.

[Logs from node-ubuntu-18](https://spruce.mongodb.com/task/drivers_atlas_testing_tests_node_ubuntu_18__driver~node_main_platform~ubuntu_18.04_runtime~node_16_validate_workload_executor_patch_eca1e9cf7de87e1493bd3ac9f18352b45e82583b_65c386af3066158dfaf390e8_24_02_07_13_33_36/logs?execution=1)
```
 [2024/02/15 03:18:12.918] http://downloads.10gen.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1804-7.2.0.tgz
 [2024/02/15 03:18:18.033] curl: (22) The requested URL returned error: 403 Forbidden
 [2024/02/15 03:18:23.065] curl: (22) The requested URL returned error: 403 Forbidden
 [2024/02/15 03:18:28.067] curl: (22) The requested URL returned error: 403 Forbidden
 [2024/02/15 03:18:28.067] tar (child): mongodb-binaries.tgz: Cannot open: No such file or directory
 [2024/02/15 03:18:28.067] tar (child): Error is not recoverable: exiting now
 ```
 
 Does this task need to run on 22.04 a well?

**Comment by alcaeus** [comment]
Update on the failures:
* MongoDB 7.2.0 (= rapid) is not available on Ubuntu 18.04, so I added a commit to use MongoDB 6.0 on that platform
* Ruby had setup failures due to an outdated version, so I switched that to Ruby 3.2
* Added the workload validator for .NET under Ubuntu for consistency
* Workload validator still fails for Ruby, .NET, and Java. Since we don't run the workload validator in nightly builds, I'll assume that this is unrelated to this PR but rather a pre-existing failure.

**Review by blink1073 — APPROVED** [review]
LGTM, thank you!

**Review by Jibola — APPROVED** [review]
LGTM! ✅✅✅ 
image

**Pull request merged**
