### PR TITLE
DRIVERS-828 Use array of objects for storeEventsAsEntities

### PR DESCRIPTION
**Pull request by jmikola**
Related to mongodb/specifications#921 and #104

cc: @DmitryLukyanov

### CODE REVIEW

**Comment by p-mongo** [comment]
Was this tested in a patch build?

**Comment by jmikola** [comment]
> Was this tested in a patch build?

I'm not familiar with patch builds for this project.

If Ruby is the only integration in this repository that has been updated for the unified test runner so far, and it hasn't been modified to accommodate this change, I assume any patch build would fail, no?

**Comment by p-mongo** [comment]
@jmikola I updated the Ruby unified test runner and tested this PR via a patch build, it passed.

**Comment by p-mongo** [comment]
To clarify, no changes are needed in the Ruby workload executor - changes were localized to unified test runner.

**Comment by p-mongo** [comment]
I am going to merge this PR since it's required for green builds now that the Ruby unified test runner was updated.

**Pull request merged**
